### PR TITLE
Use `cwd` option instead of sending a `cd`

### LINKED ISSUE #14: Clear screen after folder initialization.
Currently you see all logs with folder switching when you start a terminal, maybe it will be better to clear screen after initialization (in addition, this *currently working directory* is visible in prompt). 
Command `clear` is suitable for almost all consoles (?), and only *cmd* uses  `cls`.

I am unfamiliar with JS :) And did this as follows:

        var clearCommand = "clear";                                  // <--- Here
        var dir = path.dirname(uri.fsPath);
        var terminal = vscode.window.createTerminal();
        terminal.show(false);
        switch (kindOfShell(vscode.workspace.getConfiguration('terminal'))) {
            case "wslbash":
                // c:\workspace\foo to /mnt/c/workspace/foo
                dir = dir.replace(/(\w):/, '/mnt/$1').replace(/\\/g, '/');
                break;
            case "cmd":
                // send 1st two characters (drive letter and colon) to the terminal
                // so that drive letter is updated before running cd
                clearCommand = "cls";                                // <--- Here
                terminal.sendText(dir.slice(0, 2));
        }
        terminal.sendText("cd \"" + dir + "\"");
        terminal.sendText(clearCommand);                             // <--- Here

I can open a PR if this seems reasonable for you.

### LINKED ISSUE #17: cd Issue on different drives directories
image
if my file is on D:\ but default Terminal is pointing to C:\, cd to a folder isn't work

### PR DESCRIPTION
**Pull request by DRSDavidSoft**
## Changes
- better shell detection (e.g. relative `cmd.exe`, powershell, gitshell and cygwin in addition to wsl shell)
- change method of operation; use the `cwd` options instead of passing a `cd`

## Fixes
- fixes #17 – i.e. `cwd` does not require dos-like drive change (e.g. `d:`)
- fixes #14 – using both the suggested clear command and cwd on windows
- addresses #15 – `wsl.exe` and `ubuntu.exe` are detected (albeit they all use the default `/mnt`)

## Testing
- `cmd.exe`: tested and works
- `powershell.exe`:  tested and works
- `cygwin`: tested and works
- `git bash`: tested and works
- `wsl/1`: _not tested_
- `wsl/2`: _not tested_

Feedback on the last two are appreciated. :)

### CODE REVIEW

**Comment by DRSDavidSoft** [comment]
## Demo

### `cmd.exe`
scr-1

### `bash.exe`
scr-2

**Comment by pedrofr** [comment]
I recommend using `clsCommand = 'echo -en "\\033[1A\\033[K\\033[1A\\r\\033[K"'` or similar in the cases where the `cwd` option is not available as it emulates the behavior of the option, without interfering with possible `.bashrc`'s and other previous output.

Furthermore, I'm not sure these changes work with vscode's Remote-WSL and/or WSL 2.

Great job though! I'm using your pull request version with some ugly tweaks instead of the current release. If I had any experience with node.js I'd contribute with actual code instead of this comment...

**Comment by Tyriar** [comment]
> Furthermore, I'm not sure these changes work with vscode's Remote-WSL and/or WSL 2.

It should work provides `cwd` is passed in as a URI with the right scheme for the workspace. Not sure how I lost the notification for this PR but this should be done before it gets merged in now.

**Comment by DRSDavidSoft** [comment]
@pedrofr The escape sequences seem like a good idea! I'm not sure that `echo` on Windows is capable of throwing out those to the terminal (the same as `echo` on Linux and macOS do) -- but since Code uses xterm.js, maybe outputting them to the console using APIs would do the same.

Regarding the recent Remote containers (and WSL/2), I'd like to say that I wrote this patch before either were introduced, expecting that it would be merged soon. So I need to test this PR just to be sure.

In any case, I'd be happy to see your tweaks, as I'm sure I can learn a thing or two from your modifications.

@Tyriar No worries since you seem to be one of the most busiest people of the Code team. Thanks for all the work you do!

I actually thought that you had a better implementation in mind instead of this PR, since the APIs have had been updated since you originally made this.

I'll be glad to see input on my work, if it's still qualified to be merged.

**Comment by Tyriar** [comment]
Ok, I made a pretty radical change and removed almost all the code, it should just work now in various local shells as well as remote 🎆 published v0.2.0, let me know if you hit issues.

**Comment by pedrofr** [comment]
> In any case, I'd be happy to see your tweaks, as I'm sure I can learn a thing or two from your modifications.

@DRSDavidSoft, well... I just changed your `clsCommand` variable to be `echo -en "\\033[1A\\033[K\\033[1A\\r\\033[K"`, which isn't even optimal in what it tries to achieve. I reckon it is not portable, but I almost exclusively develop under WSL1/2 with vscode, so I didn't try to fit any other setup.

Anyway, now that it's merged the extension works elegantly as it should (at least for me)! :)

**Pull request merged**
